spring.application.name=serverMonitor
spring.datasource.url=jdbc:postgresql://localhost:5432/server_monitor
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=user_bdd
spring.datasource.password=xxx

server.port=8081

nomEnvironnement=raspberry