spring.application.name=serverMonitor

spring.datasource.url=jdbc:postgresql://localhost:5432/monitor_bdd
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=admin

#spring.jpa.hibernate.ddl-auto=validate
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
